### PR TITLE
Create merge-k-sorted-lists.cpp

### PR DESCRIPTION
**Pull request by vedant-z**

### CODE REVIEW

**Comment by vedant-z** [comment]
@avichalsri Please review this

**Review by avichalsri — CHANGES_REQUESTED** [review]
Add problem statement and example in code comments. Please read the repo guidelines in README.md

**Comment by vedant-z** [comment]
@avichalsri Sir I have made the required changes.

**Review by avichalsri — APPROVED** [review]
Changes Approved!

**Pull request merged**
