### PR TITLE
Create 3. Longest Substring Without Repeating Characters

### PR DESCRIPTION
**Pull request by manish831**

### CODE REVIEW

**Review by avichalsri — CHANGES_REQUESTED** [review]
Kindly add problem statement and example

**Review by avichalsri — APPROVED** [review]
Changes Approved

**Comment by manish831** [comment]
Sir i did all the required changes, kindly merge it now.

**Comment by manish831** [comment]
Is label of "Hactoberfest" is manually added, or it will be done later?

**Comment by avichalsri** [comment]
Added tag @manish831

**Pull request merged**
