### PR TITLE
search function in binary tree

### PR DESCRIPTION
**Pull request by smil-thakur**
hey, I made a algorithm program to find a specific element from a binary tree also you can the address of the element

### CODE REVIEW

**Comment by smil-thakur** [comment]
@avichalsri added a dsa for search function in binary tree please review it, thanks in adv

**Comment by avichalsri** [comment]
@smil-thakur good work, the code looks clean. 
Can you please share where did you find this repo from?

**Comment by smil-thakur** [comment]
yeah, I just searched hacktoberfest 2021 on github and sorted with recently updated a got your project as I am a beginner your project suited me the best so I tried to contribute,
thanks for the opportunity

**Comment by smil-thakur** [comment]
also if you can give it a hacktober-accepted tag could make my day thanks once again

**Pull request merged**
