### PR TITLE
Added kth_smallest_element.cpp file

### PR DESCRIPTION
**Pull request by rithwik003**
Signed-off-by: rithwik003 <amaraneni.rithwik@gmail.com>

### CODE REVIEW

**Review by avichalsri — CHANGES_REQUESTED** [review]
Add the problem Statement and at least 1 example in the comments above the code.

**Comment by rithwik003** [comment]
ok thank you working on it.

**Comment by rithwik003** [comment]
@avichalsri can you check it now once.

**Review by avichalsri — APPROVED** [review]
Changes Approved.

**Comment by rithwik003** [comment]
Thank you @avichalsri

**Pull request merged**
