### PR TITLE
added antiDiagonalPattern.cpp

### PR DESCRIPTION
**Pull request by awdhesh-kumar27**
added antiDiagonalPattern.cpp

Accept the PR with hactoberfest-accepted label.

### CODE REVIEW

**Comment by awdhesh-kumar27** [comment]
Please accept the PR with hactoberfest-accepted label.   ~ Newbie

**Review by avichalsri — CHANGES_REQUESTED** [review]
Kindly Add Problem statement and atleast 1 example in code comments.

**Comment by awdhesh-kumar27** [comment]
> Kindly Add Problem statement and atleast 1 example in code comments.

Above changes are done , files are updated  You can check now.

**Review by avichalsri — APPROVED** [review]
Changes Approved!

**Pull request merged**
